// <auto-generated />
using System;
using FMA.Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FMA.Application.Migrations
{
    [DbContext(typeof(FreelancerContext))]
    [Migration("20240525083440_Initial2")]
    partial class Initial2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExpertiseFreelancer", b =>
                {
                    b.Property<int>("FreelancerId")
                        .HasColumnType("integer");

                    b.Property<int>("ExpertiseId")
                        .HasColumnType("integer");

                    b.HasKey("FreelancerId", "ExpertiseId");

                    b.HasIndex("ExpertiseId");

                    b.ToTable("ExpertiseFreelancer", (string)null);

                    b.HasData(
                        new
                        {
                            FreelancerId = 1,
                            ExpertiseId = 3
                        },
                        new
                        {
                            FreelancerId = 1,
                            ExpertiseId = 1
                        },
                        new
                        {
                            FreelancerId = 1,
                            ExpertiseId = 2
                        });
                });

            modelBuilder.Entity("FMA.Application.Entities.Domain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FontFamily")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Domains");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DomainName = "Manual Labor",
                            FontFamily = "Times New Roman",
                            PhotoPath = "/images/manuallabor"
                        },
                        new
                        {
                            Id = 2,
                            DomainName = "Home Care",
                            FontFamily = "Helvetica",
                            PhotoPath = "/images/homecare"
                        },
                        new
                        {
                            Id = 3,
                            DomainName = "Health ",
                            FontFamily = "Courier New",
                            PhotoPath = "/images/health"
                        },
                        new
                        {
                            Id = 4,
                            DomainName = "White Collar Labor",
                            FontFamily = "Verdana",
                            PhotoPath = "/images/whitecollar"
                        },
                        new
                        {
                            Id = 5,
                            DomainName = "Home Repair",
                            FontFamily = "Arial",
                            PhotoPath = "/images/homerepair"
                        },
                        new
                        {
                            Id = 6,
                            DomainName = "Pet Care",
                            FontFamily = "Century Gothic",
                            PhotoPath = "/images/petcare"
                        },
                        new
                        {
                            Id = 7,
                            DomainName = "Creative",
                            FontFamily = "Cambria",
                            PhotoPath = "/images/creative"
                        });
                });

            modelBuilder.Entity("FMA.Application.Entities.Expertise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DomainId")
                        .HasColumnType("integer");

                    b.Property<string>("ExpertiseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.ToTable("Expertises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DomainId = 1,
                            ExpertiseName = "Furniture assembler"
                        },
                        new
                        {
                            Id = 2,
                            DomainId = 1,
                            ExpertiseName = "Chauffeur"
                        },
                        new
                        {
                            Id = 3,
                            DomainId = 1,
                            ExpertiseName = "Painter"
                        },
                        new
                        {
                            Id = 4,
                            DomainId = 1,
                            ExpertiseName = "Carpenter"
                        },
                        new
                        {
                            Id = 5,
                            DomainId = 1,
                            ExpertiseName = "Roof repairer"
                        },
                        new
                        {
                            Id = 6,
                            DomainId = 2,
                            ExpertiseName = "Housekeeper"
                        },
                        new
                        {
                            Id = 7,
                            DomainId = 2,
                            ExpertiseName = "Housesitter"
                        },
                        new
                        {
                            Id = 8,
                            DomainId = 2,
                            ExpertiseName = "Babysitter"
                        },
                        new
                        {
                            Id = 9,
                            DomainId = 2,
                            ExpertiseName = "Nanny"
                        },
                        new
                        {
                            Id = 10,
                            DomainId = 2,
                            ExpertiseName = "Caregiver"
                        },
                        new
                        {
                            Id = 11,
                            DomainId = 2,
                            ExpertiseName = "Cook"
                        },
                        new
                        {
                            Id = 12,
                            DomainId = 2,
                            ExpertiseName = "Kitchen cleaner"
                        },
                        new
                        {
                            Id = 13,
                            DomainId = 2,
                            ExpertiseName = "Gardener"
                        },
                        new
                        {
                            Id = 14,
                            DomainId = 2,
                            ExpertiseName = "Grocery shopper"
                        },
                        new
                        {
                            Id = 31,
                            DomainId = 3,
                            ExpertiseName = "Dance teacher"
                        });
                });

            modelBuilder.Entity("FMA.Application.Entities.Freelancer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DomainId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FulfilledContracts")
                        .HasColumnType("integer");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric");

                    b.Property<int>("HoursBilled")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.ToTable("Freelancers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateRegistered = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            DomainId = 1,
                            Email = "nadia@example.com",
                            FirstName = "Nadia",
                            FulfilledContracts = 15,
                            HourlyRate = 55m,
                            HoursBilled = 300,
                            IsActive = true,
                            LastName = "Al-Saud",
                            Latitude = 26.4207m,
                            Longitude = 50.0888m,
                            PhoneNumber = "+966504567890",
                            PhotoPath = "/images/nadia.jpg",
                            Rating = 4.7m
                        },
                        new
                        {
                            Id = 2,
                            DateRegistered = new DateTime(2024, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DomainId = 1,
                            Email = "khalid@example.com",
                            FirstName = "Khalid",
                            FulfilledContracts = 18,
                            HourlyRate = 45m,
                            HoursBilled = 350,
                            IsActive = true,
                            LastName = "Al-Farsi",
                            Latitude = 23.8859m,
                            Longitude = 45.0792m,
                            PhoneNumber = "+966509876543",
                            PhotoPath = "/images/khalid.jpg",
                            Rating = 4.6m
                        },
                        new
                        {
                            Id = 3,
                            DateRegistered = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DomainId = 1,
                            Email = "sara@example.com",
                            FirstName = "Sara",
                            FulfilledContracts = 30,
                            HourlyRate = 65m,
                            HoursBilled = 600,
                            IsActive = true,
                            LastName = "Al-Qahtani",
                            Latitude = 24.7743m,
                            Longitude = 46.7384m,
                            PhoneNumber = "+966501234567",
                            PhotoPath = "/images/sara.jpg",
                            Rating = 4.9m
                        },
                        new
                        {
                            Id = 4,
                            DateRegistered = new DateTime(2024, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DomainId = 1,
                            Email = "yousef@example.com",
                            FirstName = "Yousef",
                            FulfilledContracts = 22,
                            HourlyRate = 70m,
                            HoursBilled = 450,
                            IsActive = true,
                            LastName = "Al-Ghamdi",
                            Latitude = 21.4858m,
                            Longitude = 39.1925m,
                            PhoneNumber = "+966504321098",
                            PhotoPath = "/images/yousef.jpg",
                            Rating = 4.5m
                        },
                        new
                        {
                            Id = 5,
                            DateRegistered = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DomainId = 1,
                            Email = "layla@example.com",
                            FirstName = "Layla",
                            FulfilledContracts = 28,
                            HourlyRate = 55m,
                            HoursBilled = 550,
                            IsActive = true,
                            LastName = "Al-Omari",
                            Latitude = 26.4207m,
                            Longitude = 50.0888m,
                            PhoneNumber = "+966509876543",
                            PhotoPath = "/images/layla.jpg",
                            Rating = 4.8m
                        },
                        new
                        {
                            Id = 6,
                            DateRegistered = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DomainId = 2,
                            Email = "omar@example.com",
                            FirstName = "Omar",
                            FulfilledContracts = 19,
                            HourlyRate = 60m,
                            HoursBilled = 380,
                            IsActive = true,
                            LastName = "Al-Zahrani",
                            Latitude = 23.8859m,
                            Longitude = 45.0792m,
                            PhoneNumber = "+966501234567",
                            PhotoPath = "/images/omar.jpg",
                            Rating = 4.7m
                        },
                        new
                        {
                            Id = 7,
                            DateRegistered = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DomainId = 2,
                            Email = "huda@example.com",
                            FirstName = "Huda",
                            FulfilledContracts = 24,
                            HourlyRate = 65m,
                            HoursBilled = 500,
                            IsActive = true,
                            LastName = "Al-Muhanna",
                            Latitude = 24.7743m,
                            Longitude = 46.7384m,
                            PhoneNumber = "+966504567890",
                            PhotoPath = "/images/huda.jpg",
                            Rating = 4.6m
                        },
                        new
                        {
                            Id = 8,
                            DateRegistered = new DateTime(2024, 3, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DomainId = 2,
                            Email = "fahad@example.com",
                            FirstName = "Fahad",
                            FulfilledContracts = 32,
                            HourlyRate = 50m,
                            HoursBilled = 640,
                            IsActive = true,
                            LastName = "Al-Rashidi",
                            Latitude = 24.7136m,
                            Longitude = 46.6753m,
                            PhoneNumber = "+966501234567",
                            PhotoPath = "/images/fahad.jpg",
                            Rating = 4.9m
                        },
                        new
                        {
                            Id = 9,
                            DateRegistered = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DomainId = 2,
                            Email = "amal@example.com",
                            FirstName = "Amal",
                            FulfilledContracts = 26,
                            HourlyRate = 55m,
                            HoursBilled = 520,
                            IsActive = true,
                            LastName = "Al-Mutairi",
                            Latitude = 21.4858m,
                            Longitude = 39.1925m,
                            PhoneNumber = "+966501111222",
                            PhotoPath = "/images/amal.jpg",
                            Rating = 4.8m
                        },
                        new
                        {
                            Id = 10,
                            DateRegistered = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DomainId = 2,
                            Email = "abdullah@example.com",
                            FirstName = "Abdullah",
                            FulfilledContracts = 21,
                            HourlyRate = 70m,
                            HoursBilled = 420,
                            IsActive = true,
                            LastName = "Al-Qassem",
                            Latitude = 26.4207m,
                            Longitude = 50.0888m,
                            PhoneNumber = "+966509876543",
                            PhotoPath = "/images/abdullah.jpg",
                            Rating = 4.7m
                        },
                        new
                        {
                            Id = 11,
                            DateRegistered = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            DomainId = 2,
                            Email = "noura@example.com",
                            FirstName = "Noura",
                            FulfilledContracts = 29,
                            HourlyRate = 60m,
                            HoursBilled = 580,
                            IsActive = true,
                            LastName = "Al-Sulaiman",
                            Latitude = 23.8859m,
                            Longitude = 45.0792m,
                            PhoneNumber = "+966504321098",
                            PhotoPath = "/images/noura.jpg",
                            Rating = 4.9m
                        });
                });

            modelBuilder.Entity("ExpertiseFreelancer", b =>
                {
                    b.HasOne("FMA.Application.Entities.Expertise", null)
                        .WithMany()
                        .HasForeignKey("ExpertiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMA.Application.Entities.Freelancer", null)
                        .WithMany()
                        .HasForeignKey("FreelancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FMA.Application.Entities.Expertise", b =>
                {
                    b.HasOne("FMA.Application.Entities.Domain", "Domain")
                        .WithMany("Expertises")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("FMA.Application.Entities.Freelancer", b =>
                {
                    b.HasOne("FMA.Application.Entities.Domain", "Domain")
                        .WithMany("Freelancers")
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("FMA.Application.Entities.Domain", b =>
                {
                    b.Navigation("Expertises");

                    b.Navigation("Freelancers");
                });
#pragma warning restore 612, 618
        }
    }
}
