version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=kanaan
      - POSTGRES_PASSWORD=orjrmrorjrm
      - POSTGRES_DB=fmadb
    ports:
      - '5432:5432'